steps:
  - label: ":npm: Build"
    commands:
      - npm ci
      - npm run build
    key: build
  
  - label: ":rocket: Test"
    commands:
      - npm ci
      - npx vitest run --reporter verbose --silent=false --passWithNoTests=false || exit 1
    depends_on: build