steps:
  - label: ":npm: Installer dépendances"
    command: npm install

  - label: ":rocket: Build Vite project"
    command: npm run build

  - label: ":rocket: Compiler le projet"
    command: npm run build