steps:
  - label: ":npm: Build"
    commands:
      - npm ci
      - npm run build
    key: build
  
  - label: ":rocket: Test"
    commands:
      - npm ci
      - npx vitest run 
      - if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%
    depends_on: build